import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
//thunk action createer will generate 3 action types: 'posts/loadPosts/pending', etc for
//pending, fulfilled, and rejected

//Currently, these 3 action types have no effect on our posts slice, which would only responds 
//to action types generated by createSlice.

export const loadPosts = createAsyncThunk(
      'posts/loadPosts',
      async () => {
            const data = await fetch('https://www.reddit.com/r/popular.json');
            const json = await data.json();
            return json.data.children;
      }
);
export const loadSearchTerm = createAsyncThunk(
      'posts/loadSearchTerm', 
      async (term) => {
            const searchResults = await fetch(`https://www.reddit.com/search/?q=${term}`);
            const json = await searchResults.json();
            console.log(json);
      }
);

export const postsSlice = createSlice({
      //normally takes in an option object, but you can just create the object here
      name: 'posts',
      initialState: {
            posts: [],
            isLoading: false,
            hasError: false,
      },
      reducers: {},
      //extraReducers allows createSlice to respond to action types created by our promise
      extraReducers: {
            [loadPosts.pending]: (state, action) => {
                  state.isLoading = true;
                  state.hasError = false;
            },
            [loadPosts.fulfilled]: (state, action) => {
                  state.isLoading = false;
                  state.posts = action.payload;
            },
            [loadPosts.rejected]: (state, action) => {
                  state.isLoading = false;
                  state.hasError = true;
            }
      }
});

export const selectPosts = (state) => state.posts.posts;


export default postsSlice.reducer; 





